# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - name: set name and email
        run: git config --global user.email "997282006@qq.com"
      - name: set name 
        run: git config --global user.name "linxiaowen-i"

      - name: 导航到构建输出目录
        run: 
          cd docs/.vuepress/dist
      - name: 初始化init
        run: git init
      - name: 添加stages
        run: git add .
      
      - name: 推到 gh-pages 分支
        run: 
          git push -f git@github.com:linxiaowen-i/common-tools.git master:gh-pages
